---
# tasks file for loops

- name: with_together
  debug:
    msg: "with_together: {{ item.0 }} - {{ item.1 }}"
  with_together:
    - "{{ var_list_one }}"
    - "{{ var_list_two }}"
  tags: with_together
