---
# tasks file for system_check_sample_roles

- name: Disk check
  import_tasks: disk_check.yml

- name: Ansible facts
  import_tasks: gathering_facts.yml
  tags: gathering_facts

- name: OS check
  import_tasks: os_check.yml
  tags: os_check
